apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale-admin.fullname" . }}
  labels:
    {{- include "headscale-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: securehttp
      protocol: TCP
      name: securehttp
    - port: 2019
      targetPort: other
      protocol: TCP
      name: other
  selector:
    {{- include "headscale-admin.selectorLabels" . | nindent 4 }}
